### ISSUE TITLE
How to apply OTTL function HasAttrOnDatapoint to exclude metrics based on HttpTarget

### ISSUE THREAD

**Issue by adugar-conga** [TylerHelmuth/opentelemetry-collector-contrib#18]
### Component(s)

pkg/ottl, processor/filter, processor/resource

### Describe the issue you're reporting

Hello everyone
Otel Version : 0.73, which is compatible.

We want to exclude metrics based on a datapoint, we tried for the following 

1. Applied this : didn't work
filter/ottl:
  error_mode: ignore
  metrics:
    metric:
        - 'name == "platform.api.duration"'
        - 'type == METRIC_DATA_TYPE_HISTOGRAM'
    datapoint:
        - 'HasAttrOnDatapoint("http.target", "/connect/token")'

2. applied this : didnt work
  filter/ottl:
    metrics:
      exclude:
        match_type: expr
        expressions:
          - HasAttrOnDatapoint("HttpTarget", "/connect/token")
 
Both are not working, can you some one pls help in providing us the right expression in the yaml format ?

collector server run finished with error: invalid configuration: processors::filter/ottl: unable to parse OTTL statement: 1:65: unexpected token "<EOF>" (expected <opcomparison> Value)

can you pls let us know what is the right syntax

**Comment by adugar-conga** [comment]
@robbkidd @TylerHelmuth can you pls help ?

**Comment by TylerHelmuth** [comment]
Please open this issue in https://github.com/open-telemetry/opentelemetry-collector-contrib
